name: build-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Using Node.js v15.x
        uses: actions/setup-node@v1
        with:
          node-version: '15.x'

      - name: Installation of dependencies
        run: npm i 
      - name: Building the application
        run: npm run build
